name: Build and Push Docker Image

on:
  schedule:
    - cron: "0 0 * * *"  # Run at midnight daily
  workflow_dispatch:      # Allow manual trigger
  push:                   # Add trigger for push events

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: surfrid3r/n8n-python:latest
        platforms: linux/amd64,linux/arm64  # 添加支持多架构